# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Schön.io
email: hi@schon.io
description: > # this means to ignore newlines until "baseurl:"
  We make simple things to help you have a nice day.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://schon.io" # the base hostname & protocol for your site
twitter_username:
github_username:  schoenio

# Build settings
markdown: kramdown

# Force SSL
enforce_ssl: schon.io   # without any protocol

# Segment.com write key
segment_write_key: "G0DxlXDzkUNlmTq2ALORzm7CM8nN2kDF"

include: ['_pages']

gems:
  - jekyll-sitemap